import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Providers } from "@/store/Providers";
import Footer from "@/app/_components/shared/Footer";
import { ClerkProvider } from "@clerk/nextjs";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const clerkKey = process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY;
  const enableClerk = process.env.NEXT_PUBLIC_ENABLE_CLERK === "true";
  const hasClerkKey = typeof clerkKey === "string" && clerkKey.length > 0;
  const looksValid =
    hasClerkKey && clerkKey.startsWith("pk_") && !clerkKey.includes("dummy");
  const shouldEnableClerk = enableClerk && looksValid;
  return (
    <ClerkProvider
      dynamic
      appearance={{
        layout: {
          unsafe_disableDevelopmentModeWarnings: true,
        },
        // variables: {
        //   colorPrimary: "#5b8def",
        //   colorBackground: "#1b1c22",
        //   colorInputBackground: "#25262f",
        //   colorInputText: "#ffffff",
        //   colorText: "#ffffff",
        //   colorTextSecondary: "#6e6e6e", // dirty-grey
        // },
        // elements: {
        //   rootBox: "",
        //   cardBox: "border! border-dirty-grey!",
        //   formButtonPrimary: "bg-main-blue hover:bg-main-blue/80",
        //   headerTitle: "text-white",
        //   headerSubtitle: "text-dirty-grey",
        //   socialButtonsBlockButton:
        //     "bg-secondry-blue! text-white! hover:scale-105! hover:bg-none!",
        //   socialButtonsProviderIcon__github: "text-white!",
        //   formFieldInput:
        //     "bg-secondry-blue! border! border-white/50! text-white!",
        //   footerActionLink: "text-main-blue hover:text-main-blue/80",
        //   userButtonPopoverMain: "bg-secondry-blue!",
        //   userPreview: "border-b! border-main-blue/50!",
        // },
      }}
    >
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased bg-primary-blue`}
        >
          <Providers>{children}</Providers>
          <Footer />
        </body>
      </html>
    </ClerkProvider>
  );
}
